# Generated by Django 4.2.7 on 2023-11-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express24', '0006_shoppingcard_is_ordered_alter_shoppingcard_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
